#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Nov 14 17:03:30 2019

@author: valler
"""


import pandas as pd 
import matplotlib.pyplot as plt 
from matplotlib import gridspec 

data=pd.read_csv('Data.csv',index_col=0)








def acq(data_,m):
    tmp_m=[]
    tmp_n=[]
    i=1
    while i< 21:
        if i == 19:
            i=i+1
        else:
            tmp_m.append(data_['Ch'+str(i)].mean()*100)
            tmp_n.append(data_['Ch'+str(i)].median()*100)
            i=i+1
    tmp_m.append(data_['Other'].mean()*100)
    tmp_n.append(data_['Other'].median()*100)
    
    index=['Ch1','Ch2','Ch3','Ch4','Ch5','Ch6','Ch7','Ch8','Ch9','Ch10','Ch11','Ch12','Ch13','Ch14','Ch15','Ch16','Ch17','Ch18','Ch20','Other']
    Mean=pd.DataFrame(tmp_m,index=index)
    Mean.columns=['Mean']
    Median=pd.DataFrame(tmp_n,index=index)
    Median.columns=['Median']
    Mean=pd.concat([Mean,Median],axis=1)
    
    return Mean;


data_=data.loc[data['labels1'] == 0]
data_b=data.loc[data['labels1'] == 1]
data_c=data.loc[data['labels1'] == 2]

Meana=acq(data_,0)
Meanb=acq(data_b,1)
Meanc=acq(data_c,2)

plt.figure(figsize=(15,4))
G=gridspec.GridSpec(1,3)

ax1=plt.subplot(G[0,0])
ax2=plt.subplot(G[0,1])
ax3=plt.subplot(G[0,2])


Meana.plot.bar(ax=ax1,grid=True)

ax1.set_axisbelow(True)
ax1.set_ylabel('Mean')
ax1.set_xticks(range(len(Meana)))
ax1.set_xticklabels(Meana.index, rotation=90)
ax1.set_title('Cluster 0')


Meanb.plot.bar(ax=ax2,grid=True)
ax2.set_axisbelow(True)
ax2.set_ylabel('Median')
ax2.set_xticks(range(len(Meanb)))
ax2.set_xticklabels(Meana.index, rotation=90)
ax2.set_title('Cluster 1')
#---
Meanc.plot.bar(ax=ax3,grid=True)

ax3.set_axisbelow(True)
ax3.set_ylabel('Mean')
ax3.set_xticks(range(len(Meana)))
ax3.set_xticklabels(Meana.index,rotation=90)
ax3.set_title('Cluster 2')
